version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    volumes:
      - .:/www
      - ./docker/php/ini/:/usr/local/etc/php/dev.conf.d/

#  apache:
#    image: php:8.2-apache
#    ports:
#      - "8080:80"
#    volumes:
#      - .:/var/www/html/
#    depends_on:
#      - php
